{{- if .Values.clusterSecret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecret.name }}
spec:
  provider:
    onepassword:
      connectHost: {{ .Values.clusterSecret.connectHost }}
      vaults:
{{- range $vault := .Values.clusterSecret.vaults }}
        {{ $vault.name }}: {{ $vault.priority }}
{{- end }}
      auth:
        secretRef:
          connectTokenSecretRef:
            name: {{ .Values.clusterSecret.auth.name }}
            key: {{ .Values.clusterSecret.auth.key }}
            namespace: {{ .Values.clusterSecret.auth.namespace }}
{{- end -}}