---
# Source: bootstack-installer/templates/bootstack.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: bootstack-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
# Source: bootstack-installer/templates/bootstack.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bootstack
  namespace: bootstack-system
---
# Source: bootstack-installer/templates/bootstack.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bootstack
subjects:
- kind: ServiceAccount
  name: bootstack
  namespace: bootstack-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: bootstack-installer/templates/bootstack.yaml
apiVersion: v1
kind: Service
metadata:
  name: bootstack
  namespace: bootstack-system
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8123
  selector:
    app: bootstack
  type: ClusterIP
---
# Source: bootstack-installer/templates/bootstack.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootstack
  namespace: bootstack-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootstack
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: bootstack
    spec:
      hostNetwork: true
      serviceAccountName: bootstack
      containers:
      - name: bootstack
        image: "ghcr.io/astrasky-net/bootstack:v1.0.3"
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: localhost
        - name: KUBERNETES_SERVICE_PORT
          value: "7445"
        - name: K8S_AWAIT_ELECTION_ENABLED
          value: "1"
        - name: K8S_AWAIT_ELECTION_NAME
          value: bootstack
        - name: K8S_AWAIT_ELECTION_LOCK_NAME
          value: bootstack
        - name: K8S_AWAIT_ELECTION_LOCK_NAMESPACE
          value: bootstack-system
        - name: K8S_AWAIT_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: darkhttpd
        image: "ghcr.io/astrasky-net/bootstack:v1.0.3"
        command:
        - /usr/bin/darkhttpd
        - /bootstack/assets
        - --port
        - "8123"
        ports:
        - name: http
          containerPort: 8123
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.cilium.io/agent-not-ready"
        operator: "Exists"
        effect: "NoSchedule"
