---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confdb-backup
  namespace: confluence

spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: Confluence_DB
        property: s3_access_key

    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: Confluence_DB
        property: s3_secret_key

    - secretKey: REGION
      remoteRef:
        key: Confluence_DB
        property: s3_region
