apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confluence-license
  namespace: confluence
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: Confluence
        property: conf_license_key
