apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: confluence

spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: Confluence_DB
        property: username
    - secretKey: password
      remoteRef:
        key: Confluence_DB
        property: password
