{{- define "bootstack.namespace-anotations" }}
{{- $context := index . 0 }}
{{- $existingNS := index . 1 }}
{{- range $x := list "etcd" "monitoring" "ingress" "seaweedfs" }}
{{- if (index $context.Values $x) }}
namespace.bootstack.app/{{ $x }}: "{{ include "tenant.name" $context }}"
{{- else }}
namespace.bootstack.app/{{ $x }}: "{{ index $existingNS.metadata.annotations (printf "namespace.bootstack.app/%s" $x) | required (printf "namespace %s has no namespace.bootstack.app/%s annotation" $context.Release.Namespace $x) }}"
{{- end }}
{{- end }}
{{- end }}

{{- $existingNS := lookup "v1" "Namespace" "" .Release.Namespace }}
{{- if not $existingNS }}
{{- fail (printf "error lookup existing namespace: %s" .Release.Namespace) }}
{{- end }}

{{- if ne (include "tenant.name" .) "tenant-root" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "tenant.name" . }}
  {{- if hasPrefix "tenant-" .Release.Namespace }}
  annotations:
    {{- if .Values.host }}
    namespace.bootstack.app/host: "{{ .Values.host }}"
    {{- else }}
    {{ $parentHost := index $existingNS.metadata.annotations "namespace.bootstack.app/host" | required (printf "namespace %s has no namespace.bootstack.app/host annotation" .Release.Namespace) }}
    namespace.bootstack.app/host: "{{ splitList "-" (include "tenant.name" .) | last }}.{{ $parentHost }}"
    {{- end }}
    {{- include "bootstack.namespace-anotations" (list . $existingNS) | nindent 4 }}
  labels:
    tenant.bootstack.app/{{ include "tenant.name" $ }}: ""
    {{- if hasPrefix "tenant-" .Release.Namespace }}
    {{- $parts := splitList "-" .Release.Namespace }}
    {{- range $i, $v := $parts }}
    {{- if ne $i 0 }}
    tenant.bootstack.app/{{ join "-" (slice $parts 0 (add $i 1)) }}: ""
    {{- end }}
    {{- end }}
    {{- end }}
    {{- include "bootstack.namespace-anotations" (list $ $existingNS) | nindent 4 }}
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Namespace
    name: {{ .Release.Namespace }}
    uid: {{ $existingNS.metadata.uid }}
  {{- end }}
{{- end }}
