


confluence:
  replicaCount: 1
  fullnameOverride: confluence

  serviceAccount:
    create: true
    role:
      create: true
    clusterRole:
      create: true
    roleBinding:
      create: true
    clusterRoleBinding:
      create: true
  image:
    repository: bootstackautoio/bootstackteam-wiki
    tag: "8.9.3-ubuntu-jdk17"

  database:
    type: postgresql
    url: "jdbc:postgresql://confluence-db-rw:5432/confdb"
    credentials:
      secretName: db-credentials
      usernameSecretKey: username
      passwordSecretKey: password

  volumes:
    localHome:
      persistentVolumeClaim:
        create: true
        storageClassName: local
        resources:
          requests:
            storage: 8Gi
    sharedHome:
      persistentVolumeClaim:
        create: true
        storageClassName: local
        resources:
          requests:
            storage: 5Gi
    synchronyHome:
      persistentVolumeClaim:
        create: true
        storageClassName: local
        resources:
          requests:
            storage: 6Gi

  confluence:
    service:
      port: 8090
      type: LoadBalancer
      # sessionAffinity: ClientIP
      # sessionAffinityConfig:
      #   clientIP:
      #     timeoutSeconds: 10800
      loadBalancerIP: 
    readinessProbe:
      enabled: false
    hazelcastService:
      enabled: true
    clustering:
      enabled: false
    # s3AttachmentsStorage:
    #   bucketName: confluence-attachments
    #   bucketRegion: main
    #   endpointOverride: http://10.3.5.14:10106
    # resources:
    #   jvm:
    #     maxHeap: "4g"
    #     minHeap: "2g"
    #     reservedCodeCache: "512m"
    #     # gcAlgorithm: "UseG1GC"
    #     # maxGCPauseMillisecond: "200"
    #   container:
    #     requests:
    #       cpu: "4"
    #       memory: "8G"
    # license:
    #   secretName: confluence-license
    #   secretKey: license-key
    additionalJvmArgs:
      - "-javaagent:/opt/atlassian/atlassian-agent/atlassian-agent.jar"
      - "-Dsynchrony.service.url=https://conf.${ARGOCD_ENV_DOMAIN_NET}/synchrony/v1"
      # - "-Datlassian.plugins.enable.wait=900"
      # - "-Datlassian.recovery.password=<>"

  monitoring:
    exposeJmxMetrics: true
    serviceMonitor:
      create: true
      # prometheusLabelSelector:
      #   release: kube-prometheus-stack
    grafana:
      createDashboards: true
      dashboardLabels:
        grafana_dashboard: "1"

  synchrony:
    enabled: true
    replicaCount: 2
    readinessProbe:
      enabled: false
    service:
      port: 8091
      type: LoadBalancer
      # loadBalancerIP: 10.3.2.62
    ports:
      http: 8091

  # additionalFiles:
  #   - name: conf-storage
  #     type: secret
  #     key: credentials
  #     mountPath: /var/atlassian/application-data/confluence/.aws/

  atlassianAnalyticsAndSupport:
    analytics:
      enabled: false
    helmValues:
      enabled: true

  opensearch:
    enabled: true
    persistence:
      enabled: true
      storageClass: local
      size: 10Gi