---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jiradb-backup
  namespace: jira

spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: Minio
        property: jira_access

    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: Minio
        property: jira_key

    - secretKey: REGION
      remoteRef:
        key: Minio
        property: region
