apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-license
  namespace: jira
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: jira-license
        property: password
