---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-storage
  namespace: jira
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}

  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: Minio
        property: jira_access
    - secretKey: aws_secret_access_key
      remoteRef:
        key: Minio
        property: jira_key
