---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flowisedb-backup
  namespace: flowise

spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: Minio
        property: access key

    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: Minio
        property: secret ket

    - secretKey: REGION
      remoteRef:
        key: Minio
        property: region
