---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flowise-cr
  namespace: jira

spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: Flowise
        property: username

    - secretKey: username
      remoteRef:
        key: Flowise
        property: password
