apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flowise
  namespace: flowise
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ai.${ARGOCD_ENV_DOMAIN_NET}`)
      kind: Rule
      services:
        - name: flowise
          port: 3000
  tls: {}
