kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.0.0@sha256:ccdef06f1cae16abba105ca3a24d4db0f3d9d377df9cb8add7be20a7ad78fd57
    repository: ghcr.io/astrasky-net/kamaji
