---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: seaweedfs-db
spec:
  instances: 2
  storage:
    size: 10Gi

  inheritedMetadata:
    labels:
      policy.bootstack.app/allow-to-apiserver: "true"
