---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bootstack-system
  namespace: bootstack-system
  labels:
    bootstack.app/repository: system
spec:
  interval: 5m0s
  url: http://bootstack.bootstack-system.svc/repos/system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bootstack-apps
  namespace: bootstack-public
  labels:
    bootstack.app/ui: "true"
    bootstack.app/repository: apps
spec:
  interval: 5m0s
  url: http://bootstack.bootstack-system.svc/repos/apps
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bootstack-extra
  namespace: bootstack-public
  labels:
    bootstack.app/repository: extra
spec:
  interval: 5m0s
  url: http://bootstack.bootstack-system.svc/repos/extra
