{{- $bootstackConfig := lookup "v1" "ConfigMap" "bootstack-system" "bootstack" }}
{{- $bundleName := index $bootstackConfig.data "bundle-name" }}
{{- $bundle := tpl (.Files.Get (printf "bundles/%s.yaml" $bundleName)) . | fromYaml }}
{{- $namespaces := dict }}

{{/* collect namespaces from releases */}}
{{- range $x := $bundle.releases }}
{{- if not (hasKey $namespaces $x.namespace) }}
{{- $_ := set $namespaces $x.namespace false }}
{{- end }}
{{/* if at least one release requires a privileged namespace, then it should be privileged */}}
{{- if or $x.privileged (index $namespaces $x.namespace) }}
{{- $_ := set $namespaces $x.namespace true }}
{{- end }}
{{- end }}

{{/* Add extra namespaces */}}
{{- $_ := set $namespaces "bootstack-system" true }}
{{- $_ := set $namespaces "bootstack-public" false }}

{{- range $namespace, $privileged := $namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    bootstack.app/system: "true"
    {{- if $privileged }}
    pod-security.kubernetes.io/enforce: privileged
    {{- end }}
  name: {{ $namespace }}
{{- end }}
